version: '3.8'
services:
  # db:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     POSTGRES_DB: hmdm
  #     POSTGRES_USER: hmdm
  #     POSTGRES_PASSWORD: hmdm_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

  hmdm-server:
    build: .
    # depends_on:
    #   - db
    ports:
      - "8090:8080"
    environment:
      SQL_HOST: postgresql
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      BASE_DOMAIN: ${BASE_DOMAIN}
      LOCAL_IP: ${LOCAL_IP}
      PROTOCOL: ${PROTOCOL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SHARED_SECRET: ${SHARED_SECRET}
      HMDM_VARIANT: ${HMDM_VARIANT}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      HMDM_URL: ${HMDM_URL}
      CLIENT_VERSION: ${CLIENT_VERSION}
      FORCE_RECONFIGURE: ${FORCE_RECONFIGURE}

# volumes:
  # db_data:

